STATE_HEARTBEAT = 0
STATE_TEMPERATURE = 1
STATE_AUDIO = 2
STATE_CAMERA = 3
STATE_STEP = 4
STATE_TEXT_2_SPEECH = 5
STATE_ACTIVITY_TRIGGER = 6
STATE_ACTIVITY_TRIGGER_IMAGE = 7
STATE_ACTIVITY_TRIGGER_AUDIO = 8


STATE_ENV_ACTIVITY_CMD_TAKING_IMAGE = 10
STATE_ENV_ACTIVITY_CMD_TAKING_AUDIO = 11
STATE_ENV_ACTIVITY_CMD_TAKING_MOTION = 12
STATE_ENV_ACTIVITY_CMD_TAKING_FUSION = 13


STATE_ADL_ACTIVITY_WMU_AUDIO = 15
STATE_ADL_ACTIVITY_WMU_IMAGE = 16
STATE_ADL_ACTIVITY_WMU_MOTION = 17

# WMU_AUDIO_FILE_NOTIFICATION_FILE = '/home/ascc/asccbot_v3/medication_system/data/audio/notification.txt'
# WMU_IMAGE_FILE_NOTIFICATION_FILE = '/home/ascc/asccbot_v3/medication_system/data/images/notification.txt'



DATE_TIME_FORMAT = '%Y%m%d%H%M%S'


# WMU
WMU_IPRECEIVE = "192.168.1.131"
# WMU_IPSEND = "10.227.100.46"
WMU_IPSEND = '192.168.1.134'
#WMU_IPRECEIVE = "192.168.1.131"
#WMU_IPSEND = "192.168.1.126"
WMU_RECEIVE_PORT = 59100 # WMU server
WMU_SEND_PORT = 59000 # robot server
